frr version 7.2.1
frr defaults traditional
hostname cpe-frr
log syslog informational
no ipv6 forwarding
service integrated-vtysh-config
!
interface brint
 ip ospf mtu-ignore
!
interface net1
 ip ospf passive
!
router ospf
 network 192.168.255.0/24 area 0
 network 10.100.1.0/24 area 0
!
ip route 0.0.0.0/0 10.100.1.254
!
line vty
!